### ISSUE TITLE
New obfuscated word

### ISSUE THREAD

**Issue by p1nkyy** [idoenk/kaskus-deobfuscator#2]
tokopedia disensor jadi SENSOR.
Pls help updating the list :)

**Comment by idoenk** [comment]
wahh kalo totaly semua kata di replace, kuatir ada kata lain yg juga di mapping (replaced) menjadi "SENSOR", bisa jd miss leading…

**Comment by p1nkyy** [comment]
Wah begitu ya... ya udah deh, apa boleh buat :)
